### ISSUE TITLE
sweep_delay and "timer not started"

### ISSUE THREAD

**Issue by vincentbernat** [bioe007/awesome-shifty#13]
Hi!

When using `sweep_delay`, we can get a continuous warning about "timer not started". To reproduce this, switch to a new tag, open a terminal, close it, then switch to another tag before the sweep delay is hit. When the tag is sweeped, we get a continuous warning about "timer not started".

To fix this, make "tmr" variable local.

**Comment by bioe007** [comment]
Thanks for the feedback.

I'm not actually using awesome at the moment so a patch would welcomed.

**Comment by vincentbernat** [comment]
Here it is: https://gist.github.com/3861537

**Comment by bioe007** [comment]
Hopefully this is fixed by 1de8b879f60311461a7a35f0a38c4ab9b0b969b8

Many thanks Vincent!
