### ISSUE TITLE
Loosing focus after creating new tag in background

### ISSUE THREAD

**Issue by ghost** [bioe007/awesome-shifty#15]
Hello,

after creating one tag in background (nopopup) the focus on my current window in my current tag is lost.

I'm using the shifty package of debian (testing).

Greetings

**Comment by alfredopalhares** [comment]
Hello,
Can you provide the exact procedure ?

Also you may consider that debian is not using this repository as source. Please ensure that.

**Comment by ghost** [comment]
Hello,

sorry for the unclear description.

I'm working on tag 1 with my windows (e. g. mostly xterm). Of course one xterm window has the focus, as i'm typing in this window. Now i'm creating a new tag with Mod4+Shift+A (creating new tag in background).

This results in not leaving my current tag (as wanted) but I loose my current active (focused) window. I stil can type in xterm, but I cannot change the windows with Mod4+j/k. The only way to get back the focus to any window is by moving the mouse pointer.

Maybe the pictures below show better the situation.

I uploaded the debian file under http://pastebin.com/YQ56zgjd
The difference between this file and your repository is mostly in getpos, I think.

Thanks for your help.

![before_creating_tag](https://f.cloud.github.com/assets/1092725/6318/82ffd858-43b6-11e2-962b-a48abd5eba0e.jpg)
![after_creating_tag](https://f.cloud.github.com/assets/1092725/6319/8c5b2254-43b6-11e2-9378-18d68cc1b20f.jpg)

**Comment by bioe007** [comment]
On Tue, Dec 11, 2012 at 9:24 AM, bastorran notifications@github.com wrote:

> Hello,
> 
> sorry for the unclear description.
> 
> I'm working on tag 1 with my windows (e. g. mostly xterm). Of course one
> xterm window has the focus, as i'm typing in this window. Now i'm creating
> a new tag with Mod4+Shift+A (creating new tag in background).
> 
> This results in not leaving my current tag (as wanted) but I loose my
> current active (focused) window. I stil can type in xterm, but I cannot
> change the windows with Mod4+j/k. The only way to get back the focus to any
> window is by moving the mouse pointer.
> 
> I'm not actually using anything like this version of shifty atm, so its
> hard for me to debug, but:
- Can you gist/pastebin the keybinding and any helper functions you're
  using to generate the new tag?
- Do you have awful.autofocus enabled?
- Is the focus moved to a rename prompt?
- What happens to your client focus history? I'm looking at line 731:
  awful.client.focus.history.add(c)

as a potential problem.

## 

perry

**Comment by ghost** [comment]
Hello,

I tried now with the shifty version of this repository. But it keeps still the same.

You can find my rc.lua under: http://pastebin.com/55xNW6aF
- Keybinding is the following:
  awful.key({modkey, "Shift"  }, "a",                                    -- nopopup new tag
      function()
          shifty.add({nopopup = true})
      end),
- No, there is no focused rename prompt
- How can i check what happens to focus history?

Thanks for your help!

**Comment by bioe007** [comment]
I think PR #16  should close this.
