### ISSUE TITLE
Are you still maintaing ?

### ISSUE THREAD

**Issue by alfredopalhares** [bioe007/awesome-shifty#6]
Hello, are you still maintaining this ? I plan to add luadoc documentation to this. Do you wanna help ?

**Comment by bioe007** [comment]
First, thanks for your interest and help.

Yes, I do enough to keep it working. Can't say I have a ton of time to do much else.

Luadoc would be great, but as above I don't really have time for it right now. If there are questions I can answer though I'm happy to help that way.

I would happily push any sane patches from others and hopefully we can avoid the old nightmare of 'which shifty' to use...

My preference for new code:
- < 80 char lines
- no trailing spaces
- expand tabs

**Comment by alfredopalhares** [comment]
Great! Should i fork ? Or you can add me as member ?

**Comment by bioe007** [comment]
Added you now.

Please make all changes outside the master branch (e.g. make a doc branch) to push stuff to. Then we can test and merge.

(sorry if you know this etiquette, already I'm not trying to sound snooty)

And welcome to the shifty club :)
